// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using invetario_api.database;

#nullable disable

namespace invetario_api.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20260302233220_sales")]
    partial class sales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("invetario_api.Modules.box.entity.Box", b =>
                {
                    b.Property<int>("boxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("boxId"));

                    b.Property<decimal?>("amountClosing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("amountOpening")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("dateClosing")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateOpening")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isOpen")
                        .HasColumnType("bit");

                    b.Property<int>("userActualId")
                        .HasColumnType("int");

                    b.Property<int?>("userClosingId")
                        .HasColumnType("int");

                    b.Property<int>("userOpeningId")
                        .HasColumnType("int");

                    b.HasKey("boxId");

                    b.HasIndex("userActualId");

                    b.HasIndex("userClosingId");

                    b.HasIndex("userOpeningId");

                    b.ToTable("Boxs");
                });

            modelBuilder.Entity("invetario_api.Modules.boxMove.entity.Boxmove", b =>
                {
                    b.Property<int>("boxMoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("boxMoveId"));

                    b.Property<int>("boxId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateMove")
                        .HasColumnType("datetime2");

                    b.Property<int>("paymentMethodId")
                        .HasColumnType("int");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("boxMoveId");

                    b.HasIndex("boxId");

                    b.HasIndex("paymentMethodId");

                    b.HasIndex("userId");

                    b.ToTable("Boxmoves");
                });

            modelBuilder.Entity("invetario_api.Modules.categories.entity.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("invetario_api.Modules.client.entity.Client", b =>
                {
                    b.Property<int>("clientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clientId"));

                    b.Property<int>("clientType")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("documentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("typeDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("invetario_api.Modules.departureorder.entity.DepartureOrderDetail", b =>
                {
                    b.Property<int>("DepartureOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartureOrderDetailId"));

                    b.Property<int>("DepartureOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("departedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("lote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("storeId")
                        .HasColumnType("int");

                    b.Property<float>("unitPrice")
                        .HasColumnType("real");

                    b.Property<string>("unitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartureOrderDetailId");

                    b.HasIndex("DepartureOrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("storeId");

                    b.ToTable("DepartureOrderDetails");
                });

            modelBuilder.Entity("invetario_api.Modules.departureorder.entity.Departureorder", b =>
                {
                    b.Property<int>("departureorderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departureorderId"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("departureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("departureType")
                        .HasColumnType("int");

                    b.Property<string>("documentReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<float>("tax")
                        .HasColumnType("real");

                    b.HasKey("departureorderId");

                    b.HasIndex("clientId");

                    b.ToTable("Departureorders");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.EntryOrderDetail", b =>
                {
                    b.Property<int>("entryOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("entryOrderDetailId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("entryOrderDetailStatus")
                        .HasColumnType("int");

                    b.Property<int>("entryOrderId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<float>("unitPrice")
                        .HasColumnType("real");

                    b.HasKey("entryOrderDetailId");

                    b.HasIndex("entryOrderId");

                    b.HasIndex("productId");

                    b.ToTable("EntryOrderDetails");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.Entryorder", b =>
                {
                    b.Property<int>("entryOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("entryOrderId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("entryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("entryOrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("entryOrderType")
                        .HasColumnType("int");

                    b.Property<string>("observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("payCondition")
                        .HasColumnType("int");

                    b.Property<int>("providerId")
                        .HasColumnType("int");

                    b.Property<int>("storeId")
                        .HasColumnType("int");

                    b.Property<float>("tax")
                        .HasColumnType("real");

                    b.Property<string>("typeMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("entryOrderId");

                    b.HasIndex("providerId");

                    b.HasIndex("storeId");

                    b.ToTable("EntryOrders");
                });

            modelBuilder.Entity("invetario_api.Modules.images.entity.Images", b =>
                {
                    b.Property<int>("imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("imageId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("imageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("imageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("invetario_api.Modules.payMethod.entity.Paymethod", b =>
                {
                    b.Property<int>("paymethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymethodId"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("paymethodId");

                    b.ToTable("Paymethods");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeInternal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("imageId")
                        .HasColumnType("int");

                    b.Property<int>("minStock")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("priceBuy")
                        .HasColumnType("real");

                    b.Property<float>("priceSell")
                        .HasColumnType("real");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("unitId")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.HasIndex("imageId");

                    b.HasIndex("unitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.ProductStore", b =>
                {
                    b.Property<int>("productStoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productStoreId"));

                    b.Property<int>("actualStock")
                        .HasColumnType("int");

                    b.Property<float>("avgCost")
                        .HasColumnType("real");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("lastCost")
                        .HasColumnType("real");

                    b.Property<int>("maxStock")
                        .HasColumnType("int");

                    b.Property<int>("minStock")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("storeId")
                        .HasColumnType("int");

                    b.HasKey("productStoreId");

                    b.HasIndex("productId");

                    b.HasIndex("storeId");

                    b.ToTable("Product_Store");
                });

            modelBuilder.Entity("invetario_api.Modules.provider.entity.Provider", b =>
                {
                    b.Property<int>("providerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("providerId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("daysDelivery")
                        .HasColumnType("int");

                    b.Property<string>("documentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mainContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("payCondition")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("typeDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("providerId");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("invetario_api.Modules.sale.entity.Sale", b =>
                {
                    b.Property<int>("saleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("saleId"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<float>("total")
                        .HasColumnType("real");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("saleId");

                    b.HasIndex("clientId");

                    b.HasIndex("userId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("invetario_api.Modules.sale.entity.SaleDetails", b =>
                {
                    b.Property<int>("saleDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("saleDetailId"));

                    b.Property<decimal>("priceSell")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("saleId")
                        .HasColumnType("int");

                    b.HasKey("saleDetailId");

                    b.HasIndex("productId");

                    b.HasIndex("saleId");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("invetario_api.Modules.sale.entity.SaleMethods", b =>
                {
                    b.Property<int>("saleMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("saleMethodId"));

                    b.Property<float>("amount")
                        .HasColumnType("real");

                    b.Property<string>("methodPayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("payMethodId")
                        .HasColumnType("int");

                    b.Property<int>("saleId")
                        .HasColumnType("int");

                    b.HasKey("saleMethodId");

                    b.HasIndex("payMethodId");

                    b.HasIndex("saleId");

                    b.ToTable("SaleMethods");
                });

            modelBuilder.Entity("invetario_api.Modules.store.entity.Store", b =>
                {
                    b.Property<int>("storeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("storeId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("maxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("storeId");

                    b.HasIndex("userId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("invetario_api.Modules.storeUser.entity.Storeuser", b =>
                {
                    b.Property<int>("StoreUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("StoreUserId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Storeusers");
                });

            modelBuilder.Entity("invetario_api.Modules.unit.entity.Unit", b =>
                {
                    b.Property<int>("unitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("unitId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("unitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("invetario_api.Modules.users.entity.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("invetario_api.Modules.box.entity.Box", b =>
                {
                    b.HasOne("invetario_api.Modules.users.entity.User", "userActual")
                        .WithMany()
                        .HasForeignKey("userActualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.users.entity.User", "userClosing")
                        .WithMany()
                        .HasForeignKey("userClosingId");

                    b.HasOne("invetario_api.Modules.users.entity.User", "userOpening")
                        .WithMany()
                        .HasForeignKey("userOpeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userActual");

                    b.Navigation("userClosing");

                    b.Navigation("userOpening");
                });

            modelBuilder.Entity("invetario_api.Modules.boxMove.entity.Boxmove", b =>
                {
                    b.HasOne("invetario_api.Modules.box.entity.Box", "box")
                        .WithMany()
                        .HasForeignKey("boxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.payMethod.entity.Paymethod", "paymentMethod")
                        .WithMany()
                        .HasForeignKey("paymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.users.entity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("box");

                    b.Navigation("paymentMethod");

                    b.Navigation("user");
                });

            modelBuilder.Entity("invetario_api.Modules.departureorder.entity.DepartureOrderDetail", b =>
                {
                    b.HasOne("invetario_api.Modules.departureorder.entity.Departureorder", "Departureorder")
                        .WithMany()
                        .HasForeignKey("DepartureOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.products.entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.store.entity.Store", "Store")
                        .WithMany()
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departureorder");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("invetario_api.Modules.departureorder.entity.Departureorder", b =>
                {
                    b.HasOne("invetario_api.Modules.client.entity.Client", "client")
                        .WithMany()
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.EntryOrderDetail", b =>
                {
                    b.HasOne("invetario_api.Modules.entryorder.entity.Entryorder", "entryorder")
                        .WithMany("entryOrderDetails")
                        .HasForeignKey("entryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.products.entity.Product", "product")
                        .WithMany("entryOrderDetails")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("entryorder");

                    b.Navigation("product");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.Entryorder", b =>
                {
                    b.HasOne("invetario_api.Modules.provider.entity.Provider", "provider")
                        .WithMany("entryOrders")
                        .HasForeignKey("providerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.store.entity.Store", "store")
                        .WithMany("entryOrders")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("provider");

                    b.Navigation("store");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.Product", b =>
                {
                    b.HasOne("invetario_api.Modules.categories.entity.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.images.entity.Images", "image")
                        .WithMany("products")
                        .HasForeignKey("imageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.unit.entity.Unit", "unit")
                        .WithMany("products")
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("image");

                    b.Navigation("unit");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.ProductStore", b =>
                {
                    b.HasOne("invetario_api.Modules.products.entity.Product", "product")
                        .WithMany("productStores")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.store.entity.Store", "store")
                        .WithMany("productStores")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("store");
                });

            modelBuilder.Entity("invetario_api.Modules.sale.entity.Sale", b =>
                {
                    b.HasOne("invetario_api.Modules.client.entity.Client", "client")
                        .WithMany()
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.users.entity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("user");
                });

            modelBuilder.Entity("invetario_api.Modules.sale.entity.SaleDetails", b =>
                {
                    b.HasOne("invetario_api.Modules.products.entity.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.sale.entity.Sale", "sale")
                        .WithMany("saleDetails")
                        .HasForeignKey("saleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("sale");
                });

            modelBuilder.Entity("invetario_api.Modules.sale.entity.SaleMethods", b =>
                {
                    b.HasOne("invetario_api.Modules.payMethod.entity.Paymethod", "payMethod")
                        .WithMany()
                        .HasForeignKey("payMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.sale.entity.Sale", "sale")
                        .WithMany("saleMethods")
                        .HasForeignKey("saleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("payMethod");

                    b.Navigation("sale");
                });

            modelBuilder.Entity("invetario_api.Modules.store.entity.Store", b =>
                {
                    b.HasOne("invetario_api.Modules.users.entity.User", "user")
                        .WithMany("stores")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("invetario_api.Modules.storeUser.entity.Storeuser", b =>
                {
                    b.HasOne("invetario_api.Modules.store.entity.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.users.entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("invetario_api.Modules.categories.entity.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.Entryorder", b =>
                {
                    b.Navigation("entryOrderDetails");
                });

            modelBuilder.Entity("invetario_api.Modules.images.entity.Images", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.Product", b =>
                {
                    b.Navigation("entryOrderDetails");

                    b.Navigation("productStores");
                });

            modelBuilder.Entity("invetario_api.Modules.provider.entity.Provider", b =>
                {
                    b.Navigation("entryOrders");
                });

            modelBuilder.Entity("invetario_api.Modules.sale.entity.Sale", b =>
                {
                    b.Navigation("saleDetails");

                    b.Navigation("saleMethods");
                });

            modelBuilder.Entity("invetario_api.Modules.store.entity.Store", b =>
                {
                    b.Navigation("entryOrders");

                    b.Navigation("productStores");
                });

            modelBuilder.Entity("invetario_api.Modules.unit.entity.Unit", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("invetario_api.Modules.users.entity.User", b =>
                {
                    b.Navigation("stores");
                });
#pragma warning restore 612, 618
        }
    }
}
